[tool.poetry]
name = "nvim-remote"
version = "3.0.0"
description = "Control nvim processes using \"nvr\" commandline tool"
authors = [
  "Parham Alvani <parham.alvani@gmail.com>",
  "Marco Hinz <mh.codebro@gmail.com>",
  "Roozbeh Sharifnasab <rsharifnasab@gmail.com>",
]
license = "MIT"
readme = "README.md"
repository = "https://github.com/1995parham/nvim-remote"
keywords = ["nvim-remote", "neovim-remote", "nvr"]

[tool.poetry.dependencies]
python = ">=3.9"
pynvim = "^0.4.3"
psutil = "^5.9.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
